### ISSUE TITLE
Document Architecture 

### ISSUE THREAD

**Issue by Emilfranord** [mikkel080/BDSA-GitInsight#30]
Update your project documentation in the docs directory to reflect the latest design and architecture of your application. That is, illustrate the architecture of your tool with a suitable diagram. Additionally, based the project description so far, generate a list of functional and non-functional requirements and store them in a respective text file.

**Comment by abcras** [comment]
This is a unique task as everyone should document their own stuff. I will ofc. try to gleam the documentation from what is written in the code but in the end, it is easier if everyone does their part.

Use the DocumentArchitecture branch to access the document, if you want it to be available in your respective branch you have to go through the git hoops of committing the branch and then pulling from the main branch into your own branches which is why I haven't begun that process just yet, better to wait for the next cycle/week with new branches
